name: Feature request
description: Suggest an improvement or new feature
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the pain point or missing capability.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should Moonfin handle this?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought of.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, links, or anything else.
    validations:
      required: false
